baseURL = "https://adelzhang.github.io/"
title = "/home/adelzhang"
languageCode = "zh-cn"
languageName = "ç®€ä½“ä¸­æ–‡"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
paginate = 8

publishDir = "docs"

theme = "LoveIt"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
    post = "/:year/:slug/"

# Author config
[author]
  name = "adelzhang"
  email = ""
  link = "http://adelzhang.github.io"

[markup]
  # è¯­æ³•é«˜äº®è®¾ç½® (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false æ˜¯å¿…è¦çš„è®¾ç½® (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

# èœå•é…ç½®
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
    pre = ""
    # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
    post = ""
    name = "æ–‡ç« "
    url = "/posts/"
    # å½“ä½ å°†é¼ æ ‡æ‚¬åœåœ¨æ­¤èœå•é“¾æ¥ä¸Šæ—¶, å°†æ˜¾ç¤ºçš„æ ‡é¢˜
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "æ ‡ç­¾"
    url = "/tags/"
    title = ""


[params]
  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "/home/adelzhang"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = "ğŸ˜˜"
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false

  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/avatar.jpg"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page (HTML format is supported)
      subtitle = "ä¸å­¦æ— æœ¯ &middot; æš—äºå¤§ç†"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  [params.social]
    GitHub = "adelzhang"
    Weibo = ""
    Bilibili = ""
    Zhihu = ""
    Douban = ""
    Discord = ""
    DiscordInvite = ""
    Email = ""
    RSS = true # LoveIt NEW | 0.2.0

  [params.page]
      [params.page.share]
        enable = false